---

- name: "Restart the service for the container: {{ dashboard_checker_container_instance }}"
  service:
    name: "{{ dashboard_checker_service_label }}"
    state: restarted
  when: dashboard_checker_service_enabled|bool and dashboard_checker_restart_enabled|bool and not dashboard_checker_restart_locked|bool

- name: "Enable and run the service for the container: {{ dashboard_checker_container_instance }}"
  service:
    name: "{{ dashboard_checker_service_label }}"
    enabled: true
    state: started
  when: dashboard_checker_service_enabled|bool

- name: "Disable and stop the service for the container: {{ dashboard_checker_container_instance }}"
  service:
    name: "{{ dashboard_checker_service_label }}"
    enabled: false
    state: stopped
  when: not dashboard_checker_service_enabled|bool
