---

- name: "Pull the image for the container: {{ dashboard_checker_container_instance }}"
  docker_pull:
    name: "{{ dashboard_checker_image_source }}"
    tag: "{{ dashboard_checker_image_version }}"
    path: "{{ dashboard_checker_image_path }}"
  register: dashboard_checker_trigger_image
  when: dashboard_checker_image_manage|bool

- name: "Install the Systemd service for the container: {{ dashboard_checker_container_instance }}"
  template:
    src: systemd.service.j2
    dest: "{{ dashboard_checker_systemd_service_dir_path }}/{{ dashboard_checker_service_label }}.service"
    owner: root
    group: root
    mode: 0644
  register: dashboard_checker_trigger_systemd_service_file
  when: dashboard_checker_init_type == 'systemd'

- name: "Reload the Systemd service for the container: {{ dashboard_checker_container_instance }}"
  shell: /usr/bin/systemctl daemon-reload
  register: result
  retries: 3
  delay: 3
  until: result is success
  when: dashboard_checker_trigger_systemd_service_file|changed

- name: "Install the Systemd handler for the container: {{ dashboard_checker_container_instance }}"
  template:
    src: systemd.handler.j2
    dest: "{{ dashboard_checker_handler_prefix }}-{{ dashboard_checker_container_name }}"
    owner: root
    group: root
    mode: 0755
  when: dashboard_checker_init_type == 'systemd'
  tags:
    - handler

- name: "Notify the service for the container: {{ dashboard_checker_container_instance }}"
  set_fact:
    dashboard_checker_restart_enabled: true
  when: dashboard_checker_trigger_systemd_service_file|changed or
    dashboard_checker_trigger_upstart_service_file|changed or
    dashboard_checker_trigger_image|changed
